name: Benchmark

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binaries
        run: cargo build --release --bin bufread --bin chunks --bin default --bin io-read --bin threads

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/release

  benchmark:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Generate large text file
        run: tr -dc "A-Za-z0-9" < /dev/urandom | head -c 5G > bigfile.txt

      - name: Install hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.18.0/hyperfine-v1.18.0-aarch64-unknown-linux-gnu.tar.gz
          tar -xzvf hyperfine-v1.18.0-aarch64-unknown-linux-gnu.tar.gz
          sudo mv hyperfine /usr/local/bin/

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: target/release

      - name: Run benchmarks
        run: |
          hyperfine "./target/release/bufread bigfile.txt" \
                    "./target/release/chunks bigfile.txt" \
                    "./target/release/default bigfile.txt" \
                    "./target/release/io-read bigfile.txt" \
                    "./target/release/threads bigfile.txt"
