name: Benchmark

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binaries
        run: cargo build --release --bin bufread --bin chunks --bin default --bin io-read --bin threads

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/release

  benchmark:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # - name: Generate large text file
      #   run: |
      #     set -o pipefail
      #     tr -dc "A-Za-z0-9" < /dev/urandom | head -c 5G > bigfile.txt 2>/dev/null || true
      #     ls -lh bigfile.txt

      - name: Install hyperfine
        run: |
          FILE_NAME="hyperfine-v1.18.0-i686-unknown-linux-gnu.tar.gz"
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.18.0/$FILE_NAME
          tar -xzvf $FILE_NAME
          sudo mv $FILE_NAME/hyperfine /usr/local/bin/
          chmod +x /usr/local/bin/hyperfine

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: target/release

      - name: Run benchmarks
        run: |
          pwd
          hyperfine "./target/release/bufread README.md" \
                    "./target/release/chunks README.md" \
                    "./target/release/default README.md" \
                    "./target/release/io-read README.md" \
                    "./target/release/threads README.md"
